(function(){
 const {auth,db}=window.studyhubFirebase||{};const words=window.STUDYHUB_LEAP_WORDS||[];const setup=document.getElementById('problemSetup'),modeGrid=document.getElementById('modeGrid'),stageWrap=document.getElementById('stageWrap'),stageSelect=document.getElementById('stageSelect'),startButton=document.getElementById('startButton'),panel=document.getElementById('questionPanel'),resultPanel=document.getElementById('resultPanel'),message=document.getElementById('problemMessage'),progress=document.getElementById('questionProgress'),question=document.getElementById('questionText'),choices=document.getElementById('choices'),next=document.getElementById('nextButton'),resultTitle=document.getElementById('resultTitle'),scoreText=document.getElementById('resultScore'),rankings=document.getElementById('rankingPanel'),restart=document.getElementById('restartButton');let mode='',questions=[],index=0,score=0,answered=false;
 function shuffle(items){return [...items].sort(()=>Math.random()-.5)}
 function setupStages(){stageSelect.innerHTML='';for(let i=0;i<Math.ceil(words.length/100);i++)stageSelect.add(new Option(`ステージ${i+1}（${i*100+1}-${Math.min((i+1)*100,words.length)}語）`,String(i)))}
 function makeQuestions(pool){const selected=shuffle(pool).slice(0,10),jp=selected.slice(0,5),en=selected.slice(5,10);return [...jp.map(item=>makeQuestion(item,true,pool)),...en.map(item=>makeQuestion(item,false,pool))]}
 function makeQuestion(item,japanese,pool){const answer=japanese?item[0]:item[1],others=shuffle(pool.filter(x=>x!==item)).slice(0,3).map(x=>japanese?x[0]:x[1]);return {prompt:japanese?`${item[1]} の英語は？`:`${item[0]} の日本語は？`,answer,choices:shuffle([answer,...others])}}
 function renderQuestion(){const q=questions[index];answered=false;progress.textContent=`${index+1} / ${questions.length}問　正解: ${score}`;question.textContent=q.prompt;choices.innerHTML='';q.choices.forEach(choice=>{const button=document.createElement('button');button.className='choice';button.type='button';button.textContent=choice;button.onclick=()=>answer(button,choice,q.answer);choices.appendChild(button)});next.hidden=true}
 function answer(button,choice,answer){if(answered)return;answered=true;document.querySelectorAll('.choice').forEach(b=>{b.disabled=true;if(b.textContent===answer)b.classList.add('correct')});if(choice===answer)score++;else button.classList.add('wrong');next.hidden=false}
 async function finish(){panel.hidden=true;resultPanel.hidden=false;resultTitle.textContent=mode==='ranking'?`ステージ${Number(stageSelect.value)+1} 結果`:'自己学習 結果';scoreText.textContent=`${score} / ${questions.length}問 正解`;rankings.innerHTML='';if(mode==='ranking'){const user=await window.studyhubFirebase?.authReady;if(user&&db){const id=`${user.uid}_${stageSelect.value}`;await db.collection('leapScores').doc(id).set({uid:user.uid,stage:Number(stageSelect.value)+1,score,total:questions.length,updatedAt:new Date()},{merge:true});const snap=await db.collection('leapScores').where('stage','==',Number(stageSelect.value)+1).get();const rows=snap.docs.map(d=>d.data()).sort((a,b)=>b.score-a.score);rows.slice(0,10).forEach((row,i)=>{const div=document.createElement('div');div.className='rank-row';div.innerHTML=`<span>${i+1}位</span><strong>${row.score} / ${row.total}</strong>`;rankings.appendChild(div)});const rank=rows.findIndex(row=>row.uid===user.uid);if(rank>=10)rows.slice(Math.max(0,rank-2),rank+3).forEach(row=>{const div=document.createElement('div');div.className='rank-row';div.innerHTML=`<span>${rows.indexOf(row)+1}位（自分付近）</span><strong>${row.score} / ${row.total}</strong>`;rankings.appendChild(div)})}}}
 modeGrid.addEventListener('click',e=>{const button=e.target.closest('[data-mode]');if(!button)return;mode=button.dataset.mode;stageWrap.hidden=mode!=='ranking';startButton.hidden=false;message.textContent=mode==='ranking'?'ステージを選択して開始してください。':'全範囲から10問出題します。'});
 setup.addEventListener('submit',e=>{e.preventDefault();const pool=mode==='ranking'?words.slice(Number(stageSelect.value)*100,Number(stageSelect.value)*100+100):words;if(pool.length<10){message.textContent='問題を作るには10語以上必要です。';return}questions=makeQuestions(pool);index=0;score=0;setup.hidden=true;panel.hidden=false;resultPanel.hidden=true;renderQuestion()});next.onclick=()=>{index++;if(index>=questions.length)finish();else renderQuestion()};restart.onclick=()=>{setup.hidden=false;panel.hidden=true;resultPanel.hidden=true};setupStages();
})();
